{
  "formatVersion": "1.1",
  "component": {
    "group": "org.scijava",
    "module": "gluegen-rt",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "gluegen-rt-0.0.1.jar",
          "url": "gluegen-rt-0.0.1.jar",
          "size": 25434,
          "sha512": "f45027afd4db1459b65c9bdf3334eb79357db7ff4956ac4c94b23df87ac3f802d53c829a3e3b6e8fe2872836844ee4bbd45929940d315474f13acc1762e58639",
          "sha256": "91c0707b78c2549cec4f2172f80241430a82b3195bf9124dbbee948a88a572a7",
          "sha1": "e472d690a50f36abf893cab166a4b7cbba45c020",
          "md5": "8ce90037940c673c2af5b28abf507687"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-parent",
          "version": {
            "requires": "2.1.3.RELEASE"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.axonframework",
          "module": "axon-spring-boot-starter",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.hsqldb",
          "module": "hsqldb"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "gluegen-rt-0.0.1.jar",
          "url": "gluegen-rt-0.0.1.jar",
          "size": 25434,
          "sha512": "f45027afd4db1459b65c9bdf3334eb79357db7ff4956ac4c94b23df87ac3f802d53c829a3e3b6e8fe2872836844ee4bbd45929940d315474f13acc1762e58639",
          "sha256": "91c0707b78c2549cec4f2172f80241430a82b3195bf9124dbbee948a88a572a7",
          "sha1": "e472d690a50f36abf893cab166a4b7cbba45c020",
          "md5": "8ce90037940c673c2af5b28abf507687"
        }
      ]
    }
  ]
}
